### ISSUE TITLE
System settings

### ISSUE THREAD

**Issue by mytja** [MeetPlan/MeetPlanFrontend#10]
System settings should write to config file. Only administrator should be able to edit these settings.

Following should be in settings:
### Parents (starši)
- [x] Allow look at student's grades (dovoli vpogled v ocene)
- [x] Allow look at student's homework (dovoli vpogled v domače naloge)
- [x] Allow look at student's gradings (dovoli vpogled v ocenjevanja znanj)
- [x] Allow look at student's absences (dovoli vpogled v izostanke)
- [ ] ~Allow look at student's timetable (dovoli vpogled v urnik)~
- [ ] ~Allow look at student's self-testings (dovoli vpogled v evidenco samotestiranja)~ - we'll probably never provide it anyway
- [ ] ~Allow parent ordering meal in name of student (dovolite staršu naročati malico v učenčevem imenu)~ - i think student can order meals by themselves

### Features
- [x] Enable/disable meals

### Users (uporabniki)
- [x] Block registrations (administrator still can register new users) - Blokiraj registracije (administrator lahko še vedno registrira nove uporabnike)
- [x] All new users are unverified - Vsi novi uporabniki so ne-preverjeni

### System (sistem)
- [ ] ~School year (remove it from class) - Šolsko leto~
- [x] School name - Ime šole
- [x] School headquarters (street and house number) - Sedež šole (ulica in hišna številka)
- [x] City - Mesto
- [x] Country - Država
- [x] Post number - Poštna številka
- [ ] ~School type (primary school, high school...) - Tip šole (osnovna šola, srednja šola...)~ - not necessary
- [x] Free days (helps creating timetables and repetetive meetings) - Šole prosti dnevi (se uporabljajo pri zasnovi urnikov in ponavljajočih srečanj)
