### ISSUE TITLE
v2.2

### ISSUE THREAD

**Issue by mytja** [MeetPlan/MeetPlanFrontend#69]
## TODO
- [ ] Prestavi school_year iz `gradings` na `subject` v SQL
- [ ] Zdaj, ko imamo ime in priimek posebej, to prikaži ustrezno tudi v UI-ju (POVSOD!!!)

## Enostavno
- [ ] Naj se pri predmetih dejansko generirajo manj junky barve
- [ ] Odstrani modul za samotestiranje
- [ ] Naredi komunikacijo manj junky (drawer naj ne refresha cele strani)
- [ ] Ob odjavi naj se dejansko izbriše token, razveljavi session
- [x] Dodaj vse potrebne podatke o dijaku (davčna številka, telefonska številka)
- [ ] Renoviraj junky stran z obvestili
- [ ] Dodaj možnost za masivno generiranje PDF-jev z reseti gesel

## Srednje
- [ ] Ob prijavi učitelja ob določeni uri ga rukni iz prijave direktno na stran s pregledom na uro, če ta še ni urejena (zaključena) – to pomeni, da dodaj tudi dejansko uro poteka (npr. 9.45 do 10.30, in ne samo 1., 2., 3.)
- [ ] Naredi poenostavljeno stran s preprostim pregledom podatkov o uri (učna snov, izostanki)
- [ ] Znebi se strani "Moj pregled" pri dijaku, zamenjajo naj jo specifične strani z ocenami, napovedanimi ocenjevanji ipd.
- [ ] Uvedi možnost več sessionov z različnimi session tokeni
- [ ] Dodaj PDF izvoz vseh dijakov v oddelku (razrednik + pomočnik ravnatelja naprej)
- [ ] Dodaj možnost registracije dijaka direktno iz pogleda "Vsi uporabniki" – taka podstran naj vsebuje registracijo uporabniškega imena/elektronskega naslova (ne pa gesla) in vseh zakonsko potrebnih podatkov (davčna številka, EMŠO ...) - zgeneriraj spol in datum rojstva na podlagi EMŠO
- [ ] Dodaj možnost podpredmeta (npr. prof. pri GEO ima dostop do ocen svojega razreda tudi pri maturitetni skupini GE4, čeprav ne učita ista učitelja obeh predmetov)

## Težko
- [ ] Renoviraj stran s prehrano – dodaj tudi subvencije, pogled s stroški za dijaka, avtomatično prijavo na meni
- [x] Dodaj ocenjevanja na malo manj junky način (naj ima svoj zavihek v Drawerju)
- [ ] Popravi to sranje: `Uncaught (in promise) DOMException: Node.insertBefore: Child to insert before is not a child of this node` (zgodi se na kliku iz strani "Moj pregled" na "Pregled" na dijaškem profilu)
- [ ] Renoviraj junky "Vsi predmeti", "Vsi razredi" (loči razrede na šolska leta, dodaj možnost promocije razreda na višji razred (z možnostjo odstranitve dijakov, ki niso napredovali)) in "Vsi uporabniki" strani
- [ ] Reauditaj cel backend za potencialne vulnerabilityje in slabo kodo

## Čisto na koncu (najtežje)
- [ ] Migracija celotnega clienta na TypeScript (ko bo API za vse prej naštete stvari približno dokončan)

## V prihodnje (mogoče že v2.2, ampak verjetno ne)
- [ ] Stran z obvestili naj vsebuje targetirana obvestila (obvestila namenjena samo specifičnim – izbranim – uporabnikom)
- [ ] Ocenjevanja naj se prikažejo v urniku in dijaku
- [ ] Dodaj potrditvene dialoge na vse akcije izbrisa
- [ ] Naredi validacijo davčne številke

## Zagotovo ne v2.2, zelo verjetno v2.2.1
- [ ] Migracija na Svelte 5

**Comment by mytja** [comment]
Naj bo v3.0 dejansko 100 % pravno formalno legalna v zvezi z vso dokumentacijo (izvoz vse dokumentacije predpisane s strani ministra in CEUVIZ importi/exporti)
